### ISSUE TITLE
muteAllRemoteVideoStreams description issue

### ISSUE THREAD

**Issue by atovpeko** [AgoraIO/agora_doc_source#3558]
The `muteAllRemoteVideoStreams` API has a description issue. This API is only for video streams, but it mentions audio streams in the description. See image below
![image-2024-03-06-16-57-00-444](https://github.com/AgoraIO/agora_doc_source/assets/114177030/061fc50b-b08b-4a65-8911-abef0ea61447)

Original ticket: https://jira.agoralab.co/browse/ENDOC-113

**Comment by Cilla-luodan** [comment]
Source updated, see https://github.com/AgoraIO/Doc-Source-Private/issues/1132 for details

FYI, next time if you encounter an RTC doc issue, please create an issue or Jira (DOC) and assign it to me for a faster response.
